# Site settings
title: Álvaro Escobar
email: contacto@alvaro-escobar.dev
description: >-
  Desarrollador Full Stack y escritor técnico. 
  Apasionado por crear soluciones elegantes y compartir conocimiento.
baseurl: ""
url: "https://l3onkers.github.io"
twitter_username: 
github_username: l3onkers
linkedin_username: alvaro-escobar
hackthebox_profile: 306482

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO Tag configuration - Security hardening
seo_tag:
  generator: false

# Sass configuration for better CSS compilation
sass:
  style: compressed
  sass_dir: _sass

# Force regeneration
incremental: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Álvaro Escobar"
  - scope:
      path: ""
    values:
      layout: "default"

# Custom variables
author:
  name: Álvaro Escobar
  bio: Desarrollador Full Stack especializado en tecnologías web modernas. Apasionado por crear soluciones innovadoras y compartir conocimiento con la comunidad.
  location: España
  avatar: "https://media.licdn.com/dms/image/v2/D4D03AQFvyLxzMoW_3Q/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1677084008745?e=2147483647&v=beta&t=VIcXEJWn8VeMT0Vv7cpqwpWMoNrwfoSpagm6-Ga72IQ"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:contacto@alvaro-escobar.dev"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alvaro-escobar/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/l3onkers"
